// Generated by CoffeeScript 2.2.4
var api, app, cdn, log, watcher;

watcher = require('./watcher');

app = require('./app');

api = require('./api');

log = require('./log');

cdn = exports;

cdn.run = function(opts) {
  if (app.server) {
    throw Error('Already started');
  }
  if (opts.log != null) {
    log.set(opts.log);
  }
  return app.start().pipe(api).ready(function() {
    log.pale_green('Server ready!');
    return watcher.start();
  });
};

cdn.stop = function() {
  if (app.server) {
    app.stop();
    return watcher.stop();
  }
};

cdn.add = function(root) {
  var project;
  project = app.add(root);
  return watcher.watch(project.root);
};

cdn.remove = function(root) {
  var project;
  project = app.projects[root];
  watcher.unwatch(project.root);
  return app.remove(root);
};

//# sourceMappingURL=index.js.map
